#!/bin/bash
# ===========================================
# | AUTOSCRIPT FOR INSTALLATION SSH AND VPN |
# ===========================================
# | Owner : Administrator JasonTheKiller    |
# | Date Owned : 12/10/2018                 |
# | Telegram : t.me/JasonKiller             |
# ===========================================
echo "" 
 
read -p "Put your Username : " username
egrep "^$username" /etc/passwd >/dev/null
if [ $? -eq 0 ]; then
echo "Your username are success and registered in the VPS !"
exit 0
else
read -p "Masukkan Password [$username]: " password
masa_aktif="30"
#read -p "Expiry Date [$username] (Hari): " masa_aktif
MYIP=$(wget -qO- ipv4.icanhazip.com)
today=`date +%s`
masa_aktif_detik=$(( $masa_aktif * 86400 ))
saat_expired=$(($today + $masa_aktif_detik))
tanggal_expired=$(date -u --date="1970-01-01 $saat_expired sec GMT" +%Y/%m/%d)
tanggal_expired_display=$(date -u --date="1970-01-01 $saat_expired sec GMT" '+%d %B %Y')

echo "Welcome to ID Creator..."
sleep 0.4
echo "Creating Account..."
sleep 0.3
echo "Generating Host..."
sleep 0.2
echo "Creating Your New Username: $username"
sleep 0.2
echo "Creating Password for $username"
sleep 1


useradd $username
usermod -s /bin/false $username
usermod -e  $tanggal_expired $username
  egrep "^$username" /etc/passwd >/dev/null
  echo -e "$password\n$password" | passwd $username
  echo "Autoscript By JasonTheKiller"
  echo "THANK YOU for buying with JASONKILLER"
  echo " "
  echo "        Your Account's Details"
  echo "---------------------------------------"
  echo "   Host            : $MYIP"
  echo "   Username        : $username"
  echo "   Password        : $password"
  echo "   Masa aktif      : $masa_aktif Hari"
  echo "   Tanggal Expired : $tanggal_expired_display"
  echo "   Dropbear Port   : 109/110/443"
  echo "   OpenSSH Port    : 22/"
  echo "   Squid Proxy     : 80/8080/8000/3128"
  echo "   OpenVPN Config  : http://$MYIP/client.ovpn"
  echo "--------------------------------------"
  echo " "
fi