#!/bin/bash
# ===========================================
# | AUTOSCRIPT FOR INSTALLATION SSH AND VPN |
# ===========================================
# | Owner : Administrator JasonTheKiller    |
# | Date Owned : 12/10/2018                 |
# | Telegram : t.me/JasonKiller             |
# ===========================================

            echo ""

            chmod +x /var/lib/premium-script/data-user-pptp


            read -p "Type Username : " username
            grep -E "^$username" /var/lib/premium-script/data-user-pptp >/dev/null
            if [ $? -eq 0 ]; then
            userpass=`cat /var/lib/premium-script/data-user-pptp | grep "^$username" | awk '{print $3}'`
            saat_expired=`cat /var/lib/premium-script/data-user-pptp | grep "^$username" | awk '{print $5}'`
            tanggal_expired=$(date -u --date="1970-01-01 $saat_expired sec GMT" +%Y/%m/%d)
            tanggal_expired_display=$(date -u --date="1970-01-01 $saat_expired sec GMT" '+%d %B %Y')
            echo "loading..."
            sleep 1
            echo""
            echo "Script by JasonTheKiller"
            echo "Thank you for using our Services !"
            echo " "
            echo "Your PPTP VPN Account's Detail $Username"
            echo "---------------------------------------"
            echo "   Username        : $username"
            echo "   Password        : $userpass"
            echo "   Expired Date : $tanggal_expired_display"
            echo "--------------------------------------"
            else
            echo "Username are not exist"
            exit 1
            fi
