#!/bin/bash
# ===========================================
# | AUTOSCRIPT FOR INSTALLATION SSH AND VPN |
# ===========================================
myip=`ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0' | head -n1`;
myint=`ifconfig | grep -B1 "inet addr:$myip" | head -n1 | awk '{print $1}'`;

function create_user() {
	useradd -M $uname
	echo "$uname:$pass" | chpasswd
	usermod -e $expdate $uname

	myip=`ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0' | head -n1`;
	myip2="s/xxxxxxxxx/$myip/g";	
	wget -qO /tmp/client.ovpn "http://$myip/client.ovpn"
	sed -i 's/remote xxxxxxxxx 1194/remote xxxxxxxxx 443/g' /tmp/client.ovpn
	sed -i $myip2 /tmp/client.ovpn
	echo ""
	echo "========================="
	echo "Host IP : $myip"
	echo "Port    : 443/22/80"
	echo "Squid   : 8080/3128"
	echo "========================="

function renew_user() {
	echo "New expiration date for $uname: $expdate...";
	usermod -e $expdate $uname
}

function delete_user(){
	userdel $uname
}

function expired_users(){
	cat /etc/shadow | cut -d: -f1,8 | sed /:$/d > /tmp/expirelist.txt
	totalaccounts=`cat /tmp/expirelist.txt | wc -l`
	for((i=1; i<=$totalaccounts; i++ )); do
		tuserval=`head -n $i /tmp/expirelist.txt | tail -n 1`
		username=`echo $tuserval | cut -f1 -d:`
		userexp=`echo $tuserval | cut -f2 -d:`
		userexpireinseconds=$(( $userexp * 86400 ))
		todaystime=`date +%s`
		if [ $userexpireinseconds -lt $todaystime ] ; then
			echo $username
		fi
	done
	rm /tmp/expirelist.txt
}

function not_expired_users(){
    cat /etc/shadow | cut -d: -f1,8 | sed /:$/d > /tmp/expirelist.txt
    totalaccounts=`cat /tmp/expirelist.txt | wc -l`
    for((i=1; i<=$totalaccounts; i++ )); do
        tuserval=`head -n $i /tmp/expirelist.txt | tail -n 1`
        username=`echo $tuserval | cut -f1 -d:`
        userexp=`echo $tuserval | cut -f2 -d:`
        userexpireinseconds=$(( $userexp * 86400 ))
        todaystime=`date +%s`
        if [ $userexpireinseconds -gt $todaystime ] ; then
            echo $username
        fi
    done
	rm /tmp/expirelist.txt
}

function used_data(){
	myip=`ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0' | head -n1`
	myint=`ifconfig | grep -B1 "inet addr:$myip" | head -n1 | awk '{print $1}'`
	ifconfig $myint | grep "RX bytes" | sed -e 's/ *RX [a-z:0-9]*/Received: /g' | sed -e 's/TX [a-z:0-9]*/\nTransfered: /g'
}

	clear
	echo "--------------- WELCOME TO THE SERVER - IP : $myip ---------------"
	cname=$( awk -F: '/model name/ {name=$2} END {print name}' /proc/cpuinfo )
	cores=$( awk -F: '/model name/ {core++} END {print core}' /proc/cpuinfo )
	freq=$( awk -F: ' /cpu MHz/ {freq=$2} END {print freq}' /proc/cpuinfo )
	tram=$( free -m | awk 'NR==2 {print $2}' )
	swap=$( free -m | awk 'NR==4 {print $2}' )
	up=$(uptime|awk '{ $1=$2=$(NF-6)=$(NF-5)=$(NF-4)=$(NF-3)=$(NF-2)=$(NF-1)=$NF=""; print }')

	echo -e "\e[032;1mCPU model:\e[0m $cname"
	echo -e "\e[032;1mNumber of cores:\e[0m $cores"
	echo -e "\e[032;1mCPU frequency:\e[0m $freq MHz"
	echo -e "\e[032;1mTotal amount of ram:\e[0m $tram MB"
	echo -e "\e[032;1mTotal amount of swap:\e[0m $swap MB"
	echo -e "\e[032;1mSystem uptime:\e[0m $up"
    echo -e "\e[0;35m##########################################################################\e[0;0m"
	echo -e "\e[1;36m#                         Owner Autoscript Details                       #\e[0;0m"
	echo -e "\e[1;36m#               Creator & Owner for this Autoscript since 2017           #\e[0;0m"
	echo -e "\e[0;35m##########################################################################\e[0;0m"
	echo -e "\e[1;35m#                       MENU YANG TERDAPAT DALAM SCRIPT                  #\e[0;0m"
	echo -e "\e[0;35m##########################################################################\e[0;0m"
	echo -e "\e[031;1m# 1\e[0m) Create User SSH/VPN                                           #(\e[34;1muser-add\e[0m)"
	echo -e "\e[031;1m# 2\e[0m) Quick Generate User SSH/VPN                                   #(\e[34;1muser-gen\e[0m)"
	echo -e "\e[031;1m# 3\e[0m) Generate Trial User                                           #(\e[34;1muser-trial\e[0m)"
	echo -e "\e[031;1m# 4\e[0m) Replace User's Password                                       #(\e[34;1muser-pass\e[0m)"
	echo -e "\e[031;1m# 5\e[0m) Renew Expired User's                                          #(\e[34;1muser-renew\e[0m)"
	echo -e "\e[031;1m# 6\e[0m) Delete User's                                                 #(\e[34;1muser-del\e[0m)"
	echo -e "\e[031;1m# 7\e[0m) Check OpenSSH/Dropbear Multilogin                             #(\e[34;1muser-login\e[0m)"
	echo -e "\e[031;1m# 8\e[0m) Auto Limit Multi Login                                        #(\e[34;1mauto-limit\e[0m)"
	echo -e "\e[031;1m# 9\e[0m) Details Of SSH/VPN User's                                     #(\e[34;1muser-detail\e[0m)"
	echo -e "\e[031;1m#10\e[0m) Delete Expired User's                                         #(\e[34;1mdelete-user-expire\e[0m)"
	echo -e "\e[031;1m#11\e[0m) Kill Multilogin                                               #(\e[34;1mauto-kill-user\e[0m)"
	echo -e "\e[031;1m#12\e[0m) Auto Banned User's                                            #(\e[34;1mbanned-user\e[0m)"
	echo -e "\e[031;1m#13\e[0m) Unbanned User's                                               #(\e[34;1munbanned-user\e[0m)"
	echo -e "\e[031;1m#14\e[0m) Lock SSH/VPN User's                                           #(\e[34;1muser-lock\e[0m)"
	echo -e "\e[031;1m#15\e[0m) Unlock the Locked SSH/VPN User's                              #(\e[34;1muser-unlock\e[0m)"
	echo -e "\e[031;1m#16\e[0m) List of User's that are locked by LIMIT                       #(\e[34;1mlog-limit\e[0m)"
	echo -e "\e[031;1m#17\e[0m) List of User's that are locked by BAN                         #(\e[34;1mlog-ban\e[0m)"
	echo -e "\e[031;1m#18\e[0m) Create PPTP VPN User's                                        #(\e[34;1muser-add-pptp\e[0m)"
	echo -e "\e[031;1m#19\e[0m) Delete PPTP VPN's User                                        #(\e[34;1muser-delete-pptp\e[0m)"
	echo -e "\e[031;1m#20\e[0m) PPTP VPN's Details                                            #(\e[34;1mdetail-pptp\e[0m)"
	echo -e "\e[031;1m#21\e[0m) Check Login PPTP VPN                                          #(\e[34;1muser-login-pptp\e[0m)"
	echo -e "\e[031;1m#22\e[0m) List of Registered PPTP VPN                                   #(\e[34;1malluser-pptp\e[0m)"
	echo -e "\e[031;1m#23\e[0m) Set Auto Reboot                                               #(\e[34;1mauto-reboot\e[0m)"
	echo -e "\e[031;1m#24\e[0m) Speedtest                                                     #(\e[34;1mcek-speedttes-vps\e[0m)"
	echo -e "\e[031;1m#25\e[0m) Memory Usage                                                  #(\e[34;1mps-mem\e[0m)"
	echo -e "\e[031;1m#26\e[0m) Change OpenVPN Port                                           #(\e[34;1mchange-openvpn-port\e[0m)"
	echo -e "\e[031;1m#27\e[0m) Change Dropbear Port                                          #(\e[34;1mchange-dropbear-port\e[0m)"
	echo -e "\e[031;1m#28\e[0m) Change Squid Port                                             #(\e[34;1mchange-squid-port\e[0m)"
	echo -e "\e[031;1m#29\e[0m) Restart OpenVPN                                               #(\e[34;1mrestart-openvpn\e[0m)"
	echo -e "\e[031;1m#30\e[0m) Restart Dropbear                                              #(\e[34;1mrestart-dropbear\e[0m)"
	echo -e "\e[031;1m#31\e[0m) Restart Squid                                                 #(\e[34;1mrestart-squid\e[0m)"
	echo -e "\e[031;1m#32\e[0m) Restart Webmin                                                #(\e[34;1mrestart-webmin\e[0m)"
	echo -e "\e[031;1m#33\e[0m) Benchmark                                                     #(\e[34;1mbenchmark\e[0m)"
	echo -e "\e[031;1m#34\e[0m) Change Pasword VPS                                            #(\e[34;1mpassword\e[0m)"
	echo -e "\e[031;1m#35\e[0m) Change Hostname VPS                                           #(\e[34;1mhostname\e[0m)"
	echo -e "\e[031;1m#36\e[0m) Reboot Server                                                 #(\e[34;1mreboot\e[0m)"
	echo -e "\e[031;1m# x\e[0m) Exit                                                          #"
	echo -e "\e[0;35m##########################################################################\e[0;0m"
	read -p "Choose your desired options and ENTER : " option1
	case $option1 in
        1)  
            clear
            buatakun
            ;;
        2)  
            clear
            generate
            ;;
        3)	
            clear
            trial
			;;	
        4)
            clear
            userpass
            ;;
        5)
            clear
            userrenew
			;;
        6)
            userdelete
            ;;		
		7)
		    clear
	        userlogin
			;;
		8)
		    clear
			autolimit
			;;	
		9)
		    clear
            userdetail
            ;;
        10)
               clear
               deleteuserexpire
	          ;;
	    11)
	          clear
	          #!/bin/bash
               echo ""
	           echo "    AUTO KILL MULTI LOGIN    "    
	           echo "-----------------------------"
               autokilluser
               echo "-----------------------------"
               echo "AUTO KILL MULTI LOGIN SELESAI"
               ;;
        12)
               clear
               userban
	          ;;
	    13)
               clear
               userunban
	          ;;
	    14)
	        clear
            userlock
			;;
		15)
		    clear
            userunlock
			;;
		16)
		    clear
		    loglimit
			;;
		17)
		    clear
            logban
			;;
	    18)
	        clear
            useraddpptp
			;;
		19)
		    clear
            userdeletepptp
			;;
	    20)
	        clear
            detailpptp
            ;;
        21)
            clear
            userloginpptp
			;;
		22)
		    clear
            alluserpptp
			;;
	    23)
	         clear
             autoreboot
            ;;
	    24)
	         clear
            echo ""
            echo "Speed Test Server"
            ./speedtest.py --share
            echo "Est.Speedtest..."
            ;;
        25)
            ps-mem
            ;;
		26)	
		    clear
            echo "Masukan Port OpenVPN yang diinginkan:"
            read -p "Port: " -e -i 1194 PORT
            sed -i "s/port [0-9]*/port $PORT/" /etc/openvpn/1194.conf
            service openvpn restart
            echo "OpenVPN Updated : Port $PORT"
			;;
		27)	
		    clear
            echo "Masukan Port Dropbear yang diinginkan:"
            read -p "Port: " -e -i 443 PORT
            sed -i "s/DROPBEAR_PORT=[0-9]*/DROPBEAR_PORT=$PORT/" /etc/default/dropbear
            service dropbear restart
            echo "Dropbear Updated : Port $PORT"
			;;
        28)	
            clear
            echo "Masukan Port Squid yang diinginkan:"
            read -p "Port: " -e -i 8080 PORT
            sed -i "s/http_port [0-9]*/http_port $PORT/" /etc/squid3/squid.conf
            service squid3 restart
            echo "echo "Squid3 Updated : Port $PORT""
			;;			
        29)	
            clear
            echo "Service Openvpn restart .................tunggu sebentar"
            service openvpn restart
            echo "Restart OpenVPN selesai"
			;;	
		30)
            clear
            echo "Servie dropbear restart .................tunggu sebentar"
            service dropbear restart
            echo "Restart Dropbear selesai"
            ;;
		31) 
		    clear
		    echo "Service Squid restart .................tunggu sebentar"
			service squid3 restart
			echo "Restart Squid selesai"
			;;
		32)
		    clear
		    /etc/init.d/webmin restart
		    echo "Restart Webmin selesai"
		    ;;
		33)
		    clear
            wget freevps.us/downloads/bench.sh -O - -o /dev/null|bash
           ;;
        34)
		    echo "Masukan Password VPS, yang mau diganti :"
		    passwd
			;;	
		35)
			echo "Masukan HOSTNAME VPS, yang mau diganti :"
            echo "  contoh : " hostname AutoscriptVPS 
            ;;
		36)
		    clear
			reboot
            ;;
		37)
			clear
			echo -e "\e[0;34m CHOOSE WHAT LIST YOU WANT ! (1-3)  \e[0;0m"
		
			echo "1) DAILY"
			read -p "1"
			vnstat -d
		
			echo "2) WEEKLY"
			read -p "2"
			vnstat -w
		
			echo "3) MONTHLY"
			read -p "3"
			vnstat -m
	
			echo -e "Press 0 to exit"
			read -p "0"
			exit
			;;
        x)
            ;;
        *) menu;;
    esac