#!/bin/bash
# ===========================================
# | AUTOSCRIPT FOR INSTALLATION SSH AND VPN |
# ===========================================
# | Owner : Administrator JasonTheKiller    |
# | Date Owned : 12/10/2018                 |
# | Telegram : t.me/JasonKiller             |
# ===========================================

               echo ""


               read -p "Type the USERNAME that you want to UNBAN : " username
               egrep "^$username" /etc/passwd >/dev/null
               if [ $? -eq 0 ]; then
               # proses mengganti passwordnya
               passwd -u $username
               echo""
               echo "Autoscript by JasonTheKiller"
               echo "Thank you for unban the users"
               echo " "
               echo "-----------------------------------------------"
               echo -e "Username ${blue}$username${NC} are unban ! ${green}UNBAN${NC}."
               echo -e "Password for Username ${blue}$username${NC} are accessily now !"
               echo "-----------------------------------------------"
               else
               echo "Username are not found/exist"
               exit 1
               fi