#!/bin/bash
# ===========================================
# | AUTOSCRIPT FOR INSTALLATION SSH AND VPN |
# ===========================================
# | Owner : Administrator JasonTheKiller    |
# | Date Owned : 12/10/2018                 |
# | Telegram : t.me/JasonKiller             |
# ===========================================

            echo ""

            read -p "Type the USERNAME you want to LOCK : " username
            egrep "^$username" /etc/passwd >/dev/null
            if [ $? -eq 0 ]; then
            # proses mengganti passwordnya
            passwd -l $username
            echo""
            echo "Autoscript by JasonTheKiller"
            echo "Thank you for locking the users"
            echo " "
            echo "-----------------------------------------------"
            echo -e "Username ${blue}$username${NC} are locked now ! ${red}KUNCI${NC}."
            echo -e "This ID  ${blue}$username${NC} are blocked from access !"
            echo "-----------------------------------------------"
            else
            echo "Username not found/not exist"
            exit 1
            fi
